// --- SHARED FORMAT GENERATORS ---
// Used by both popup.js and utilities.js

function generateJSON(cookies) { return JSON.stringify(cookies, null, 2); }

function generateNetscape(cookies) {
    let str = "# Netscape HTTP Cookie File\n# This file was generated by Neeno's Cookie Importer\n";
    const lines = cookies.map(c => {
        const prefix = c.httpOnly ? '#HttpOnly_' : '';
        const domain = c.domain || '';
        const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
        const path = c.path || '/';
        const secure = c.secure ? 'TRUE' : 'FALSE';
        const expiration = Math.round(c.expirationDate || c.expiration || 0);
        const name = c.name;
        const value = c.value;
        return `${prefix}${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expiration}\t${name}\t${value}`;
    });
    return str + lines.join('\n');
}

function generateHeaderString(cookies) { return cookies.map(c => `${c.name}=${c.value}`).join('; '); }

function generatePuppeteer(cookies) {
    const pupCookies = cookies.map(c => ({
        name: c.name, value: c.value, domain: c.domain, path: c.path,
        expires: c.expirationDate || c.expiration || -1, httpOnly: c.httpOnly, secure: c.secure,
        sameSite: c.sameSite === 'no_restriction' ? 'None' : (c.sameSite === 'unspecified' ? undefined : c.sameSite)
    }));
    return JSON.stringify(pupCookies, null, 2);
}

function generatePython(cookies) {
    const lines = cookies.map(c => {
        const safeName = c.name.replace(/'/g, "\\'");
        const safeValue = c.value.replace(/'/g, "\\'");
        return `'${safeName}': '${safeValue}'`;
    });
    return "{\n  " + lines.join(',\n  ') + "\n}";
}

function generateCSV(cookies) {
    const header = "Name,Value,Domain,Path,Secure,HttpOnly,SameSite,Expiration\n";
    const rows = cookies.map(c => {
        const escapeCSV = (val) => {
            if (typeof val !== 'string') val = String(val);
            if (val.includes(',') || val.includes('"') || val.includes('\n')) {
                return `"${val.replace(/"/g, '""')}"`;
            }
            return val;
        };
        return [escapeCSV(c.name), escapeCSV(c.value), escapeCSV(c.domain), escapeCSV(c.path), c.secure, c.httpOnly, c.sameSite, Math.round(c.expirationDate || c.expiration || 0)].join(',');
    });
    return header + rows.join('\n');
}

// --- FORMAT DETECTION (standalone) ---
function detectFormat(input) {
    const str = (input || '').trim();
    if (!str) return 'Unknown';

    // CSV: check for header row pattern
    if (/^Name,Value,Domain/i.test(str) || /^"?Name"?,"?Value"?,"?Domain"?/i.test(str)) return 'CSV';

    // JSON-based formats
    if (str.startsWith('[') || str.startsWith('{')) {
        try {
            const parsed = JSON.parse(str);
            const arr = Array.isArray(parsed) ? parsed : [parsed];
            if (arr.length > 0 && arr[0]) {
                // Puppeteer uses "expires" (number), standard JSON uses "expirationDate"
                if ('expires' in arr[0] && typeof arr[0].expires === 'number') return 'Puppeteer';
            }
            return 'JSON';
        } catch (e) {
            // Could be Python dict with single quotes
            if (str.startsWith('{') && str.includes("'") && !str.includes('"')) {
                try {
                    JSON.parse(str.replace(/'/g, '"'));
                    return 'Python Dict';
                } catch { /* fall through */ }
            }
        }
    }

    // Netscape: tab-separated or starts with # comment
    if (str.includes('\t') && str.split('\n').some(l => l.split('\t').length >= 6)) return 'Netscape';
    if (str.startsWith('# Netscape') || str.startsWith('#HttpOnly_')) return 'Netscape';

    // Header string: key=value; key=value pairs
    if (/^[\w\-.]+=.+;\s*[\w\-.]+=/.test(str)) return 'Header String';

    // CSV fallback: comma-separated lines with multiple columns
    const csvLines = str.split('\n').filter(l => l.trim());
    if (csvLines.length > 1 && csvLines.every(l => l.split(',').length >= 3)) return 'CSV';

    return 'Unknown';
}
